# dictionary of emotions
emoj_dict = {
    "happy": ":smiling_face_with_smiling_eyes:",
    "anger": ":angry_face:",
    "fear": ":fearful_face:",
    "sad": ":crying_face:",
    "surprise": ":astonished_face:",
    "love": ":red_heart:",
    "fine": ":OK_hand:",
    "worry": ":worried_face:",
    "hot": ":hot_face:",
    "sick": ":sneezing_face:",
    "cry": ":crying_face:",
    "meh": ":disappointed_face:",
    "yawn": ":yawning_face:",
    "laugh": ":face_with_tears_of_joy:",
    "shock": ":exploding_head:",
}

# dictionary of key-words associated with emotions
kw_dict = {
    "bored": "yawn",
    "tired": "yawn",
    "yawning": "yawn",
    "smiling": "happy",
    "relaxed": "happy",
    "joyful": "happy",
    "pleased": "happy",
    "delighted": "happy",
    "happy": "happy",
    "satisfied": "happy",
    "angry": "anger",
    "mad": "anger",
    "frown": "anger",
    "afraid": "fear",
    "scared": "fear",
    "horrible": "fear",
    "sad": "sad",
    "unhappy": "sad",
    "depressed": "sad",
    "miserable": "sad",
    "heartbroken": "sad",
    "yearn": "sad",
    "missing": "sad",
    "yearning": "sad",
    "upset": "sad",
    "distracted": "sad",
    "out of tune": "sad",
    "surprised": "surprise",
    "astonished": "surprise",
    "love": "love",
    "loving": "love",
    "fine": "fine",
    "ok": "fine",
    "very well": "fine",
    "disappointed": "meh",
    "skeptical": "meh",
    "unsure": "meh",
    "bored": "yawn",
    "tired": "yawn",
    "yawning": "yawn",
    "yawn": "yawn",
    "sleepy": "yawn",
    "sick": "sick",
    "sneeze": "sick",
    "crying": "cry",
    "cried": "cry",
    "cry": "cry",
    "weeping": "cry",
    "weep": "cry",
    "worry": "worry",
    "worried": "worry",
    "laugh": "laugh",
    "laughing": "laugh",
    "mind blown": "shock",
    "shocked": "shock",
    "shock": "shock",
    "nervous": "worry"
}
