insert into comments (user_id, post_id, comment) values (7, 16, 'Mauris sit amet eros.');
insert into comments (user_id, post_id, comment) values (2, 32, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into comments (user_id, post_id, comment) values (8, 11, 'Nunc nisl.');
insert into comments (user_id, post_id, comment) values (2, 22, 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into comments (user_id, post_id, comment) values (10, 18, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, comment) values (10, 20, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into comments (user_id, post_id, comment) values (4, 4, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into comments (user_id, post_id, comment) values (1, 22, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, comment) values (3, 16, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into comments (user_id, post_id, comment) values (2, 3, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, comment) values (7, 20, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into comments (user_id, post_id, comment) values (4, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into comments (user_id, post_id, comment) values (7, 3, 'Nunc purus.');
insert into comments (user_id, post_id, comment) values (3, 3, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, comment) values (8, 34, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, comment) values (3, 3, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into comments (user_id, post_id, comment) values (7, 22, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, comment) values (6, 32, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into comments (user_id, post_id, comment) values (8, 24, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into comments (user_id, post_id, comment) values (9, 33, 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, comment) values (3, 24, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into comments (user_id, post_id, comment) values (2, 26, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
insert into comments (user_id, post_id, comment) values (9, 21, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
insert into comments (user_id, post_id, comment) values (2, 13, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into comments (user_id, post_id, comment) values (10, 26, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into comments (user_id, post_id, comment) values (3, 16, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, comment) values (9, 34, 'Praesent id massa id nisl venenatis lacinia.');
insert into comments (user_id, post_id, comment) values (2, 32, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into comments (user_id, post_id, comment) values (7, 20, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into comments (user_id, post_id, comment) values (5, 5, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.');
insert into comments (user_id, post_id, comment) values (10, 10, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into comments (user_id, post_id, comment) values (7, 29, 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.');
insert into comments (user_id, post_id, comment) values (6, 17, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, comment) values (8, 6, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into comments (user_id, post_id, comment) values (2, 28, 'Integer tincidunt ante vel ipsum.');
insert into comments (user_id, post_id, comment) values (6, 23, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into comments (user_id, post_id, comment) values (9, 31, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into comments (user_id, post_id, comment) values (1, 26, 'Duis mattis egestas metus. Aenean fermentum.');
insert into comments (user_id, post_id, comment) values (10, 15, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into comments (user_id, post_id, comment) values (3, 12, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into comments (user_id, post_id, comment) values (10, 14, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into comments (user_id, post_id, comment) values (5, 27, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into comments (user_id, post_id, comment) values (8, 33, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.');
insert into comments (user_id, post_id, comment) values (5, 30, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into comments (user_id, post_id, comment) values (3, 22, 'Fusce consequat. Nulla nisl.');
insert into comments (user_id, post_id, comment) values (9, 10, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into comments (user_id, post_id, comment) values (10, 15, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into comments (user_id, post_id, comment) values (4, 33, 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, comment) values (6, 33, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, comment) values (9, 23, 'Fusce posuere felis sed lacus.');
insert into comments (user_id, post_id, comment) values (9, 31, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, comment) values (1, 13, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into comments (user_id, post_id, comment) values (9, 33, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into comments (user_id, post_id, comment) values (10, 19, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into comments (user_id, post_id, comment) values (1, 25, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, comment) values (5, 12, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into comments (user_id, post_id, comment) values (1, 27, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into comments (user_id, post_id, comment) values (1, 20, 'Nulla nisl. Nunc nisl.');
insert into comments (user_id, post_id, comment) values (6, 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into comments (user_id, post_id, comment) values (2, 28, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into comments (user_id, post_id, comment) values (6, 24, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into comments (user_id, post_id, comment) values (9, 20, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into comments (user_id, post_id, comment) values (10, 26, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into comments (user_id, post_id, comment) values (7, 30, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into comments (user_id, post_id, comment) values (3, 25, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into comments (user_id, post_id, comment) values (2, 22, 'Nulla nisl. Nunc nisl.');
insert into comments (user_id, post_id, comment) values (5, 29, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, comment) values (1, 8, 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, comment) values (7, 9, 'Morbi a ipsum.');
insert into comments (user_id, post_id, comment) values (9, 5, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into comments (user_id, post_id, comment) values (9, 29, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into comments (user_id, post_id, comment) values (6, 20, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into comments (user_id, post_id, comment) values (2, 7, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into comments (user_id, post_id, comment) values (6, 15, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into comments (user_id, post_id, comment) values (9, 13, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into comments (user_id, post_id, comment) values (2, 32, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into comments (user_id, post_id, comment) values (9, 32, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, comment) values (9, 2, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, comment) values (1, 29, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into comments (user_id, post_id, comment) values (8, 12, 'Suspendisse potenti.');
insert into comments (user_id, post_id, comment) values (2, 23, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into comments (user_id, post_id, comment) values (2, 33, 'Pellentesque at nulla. Suspendisse potenti.');
insert into comments (user_id, post_id, comment) values (3, 8, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into comments (user_id, post_id, comment) values (9, 4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into comments (user_id, post_id, comment) values (3, 26, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into comments (user_id, post_id, comment) values (2, 19, 'Fusce posuere felis sed lacus.');
insert into comments (user_id, post_id, comment) values (5, 24, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, comment) values (2, 22, 'Praesent blandit.');
insert into comments (user_id, post_id, comment) values (1, 34, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, comment) values (1, 19, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, comment) values (10, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into comments (user_id, post_id, comment) values (9, 23, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, comment) values (5, 18, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into comments (user_id, post_id, comment) values (3, 12, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, comment) values (3, 18, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into comments (user_id, post_id, comment) values (2, 27, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into comments (user_id, post_id, comment) values (7, 6, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, comment) values (7, 11, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, comment) values (2, 13, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, comment) values (6, 6, 'Aenean lectus.');
